# -*- coding: utf-8 -*-
"""Model_Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-l48LEZ7qFaFPc9b7QLKfo8-9NdUSqMN
"""

# =============================
# 1. INSTALL DEPENDENCIES
# =============================
!pip install xgboost scikit-learn pandas

# =============================
# 2. IMPORT LIBRARIES
# =============================
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# =============================
# 3. LOAD YOUR CLEANED DATA
# =============================
from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])

# =============================
# 4. SELECT FEATURES & TARGET
# =============================
features = ["Make", "Model", "EV_Type", "CAFV_Eligibility",
            "Vehicle_Age", "Electric_Utility"]

target = "Electric_Range"

df = df.dropna(subset=[target])  # Remove rows with no range

X = df[features]
y = df[target]

# =============================
# 5. PREPROCESSING (ONE-HOT ENCODING)
# =============================
categorical = ["Make", "Model", "EV_Type", "CAFV_Eligibility", "Electric_Utility"]
numeric = ["Vehicle_Age"]

preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
        ("num", "passthrough", numeric)
    ]
)

# =============================
# 6. BUILD XGBOOST PIPELINE
# =============================
model = Pipeline(steps=[
    ("preprocess", preprocess),
    ("xgb", XGBRegressor(
        n_estimators=350,
        learning_rate=0.06,
        max_depth=8,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    ))
])

# =============================
# 7. TRAIN/TEST SPLIT
# =============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

# =============================
# 8. TRAIN THE MODEL
# =============================
model.fit(X_train, y_train)

# =============================
# 9. EVALUATE
# =============================
preds = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))
print("R² Score:", r2_score(y_test, preds))

# =============================
# 10. SAVE MODEL FOR DEPLOYMENT
# =============================
import joblib
joblib.dump(model, "electric_range_model.pkl")

print("Model saved as electric_range_model.pkl")